### PR TITLE
Fix data streaming errors when streaming to CSV

### LINKED ISSUE #183: Error streaming to CSV.Sink
Streaming to CSV gives me an error although `ODBC.query(dsn, qry)` works just fine

```
using ODBC, CSV

qry = """
select * from someschema.sometable limit 100
"""

dsn = ODBC.DSN("someDSN")
csv = ODBC.query(dsn, qry, CSV.Sink, "myfile.csv")

ERROR: MethodError: no method matching CSV.Sink(::DataStreams.Data.Schema{true,Tuple{Union{Missings.Missing, String},Union{Missings.Missing, ODBC.API.SQLTimestamp},Union{Missings.Missing, ODBC.API.SQLTimestamp},Union{Missings.Missing, String},Union{Int16, Missings.Missing}}}, ::Type{DataStreams.Data.Field}, ::Bool, ::Tuple{String}; reference=UInt8[])
Closest candidates are:
  CSV.Sink(::DataStreams.Data.Schema, ::Any, ::Any, ::AbstractString; reference, kwargs...) at C:\Users\username\.julia\v0.6\CSV\src\Sink.jl:37
  CSV.Sink(::Any, ::DataStreams.Data.Schema, ::Any, ::Any; reference) at C:\Users\username\.julia\v0.6\CSV\src\Sink.jl:42
Stacktrace:
 [1] #stream!#17(::Bool, ::Dict{Int64,Function}, ::Function, ::Array{Any,1}, ::Array{Any,1}, ::Function, ::ODBC.Source{Tuple{Array{Union{Missings.Missing, String},1},Array{Union{Missings.Missing, ODBC.API.SQLTimestamp},1},Array{Union{Missings.Missing, ODBC.API.SQLTimestamp},1},Array{Union{Missings.Missing, String},1},Array{Union{Int16, Missings.Missing},1}}}, ::Type{CSV.Sink}, ::Tuple{String}, ::Vararg{Tuple{String},N} where N) at C:\Users\username\.julia\v0.6\DataStreams\src\DataStreams.jl:483
 [2] (::DataStreams.Data.#kw##stream!)(::Array{Any,1}, ::DataStreams.Data.#stream!, ::ODBC.Source{Tuple{Array{Union{Missings.Missing, String},1},Array{Union{Missings.Missing, ODBC.API.SQLTimestamp},1},Array{Union{Missings.Missing, ODBC.API.SQLTimestamp},1},Array{Union{Missings.Missing, String},1},Array{Union{Int16, Missings.Missing},1}}}, ::Type{CSV.Sink}, ::Tuple{String}, ::Vararg{Tuple{String},N} where N) at .\<missing>:0
 [3] #query#13(::Bool, ::Bool, ::Dict{Int64,Function}, ::Function, ::ODBC.DSN, ::String, ::Type{T} where T, ::String, ::Vararg{String,N} where N) at C:\Users\username\.julia\v0.6\ODBC\src\Source.jl:342
 [4] query(::ODBC.DSN, ::String, ::Type{T} where T, ::String, ::Vararg{String,N} where N) at C:\Users\username\.julia\v0.6\ODBC\src\Source.jl:342
 [5] eval(::Module, ::Any) at .\boot.jl:235
```

I'm on Julia 0.6.2, package versions:
```
- CSV                           0.2.1
- ODBC                          0.6.0
- DataStreams                   0.3.4
```

### LINKED ISSUE #196: Data Streaming BoundsError
Get a BoundsError when attempting to stream data to CSV and SQLite:

```julia
BoundsError: attempt to access 0-element Array{Union{Int64, Missings.Missing},1} at index [1]
  Stacktrace:
   [1] getindex(::Array{Union{Int64, Missings.Missing},1}, ::Int64) at ./array.jl:554
   [2] streamfrom(::ODBC.Source{Tuple{Array{Union{Int64, Missings.Missing},1},Array{Union{Int8, Missings.Missing},1},Array{Union{DecFP.Dec64, Missings.Missing},1},Array{Union{Int32, Missings.Missing},1},Array{Union{DecFP.Dec64, Missings.Missing},1},Array{Union{Int16, Missings.Missing},1},Array{Union{Int32, Missings.Missing},1},Array{Union{Int8, Missings.Missing},1},Array{Union{Float32, Missings.Missing},1},Array{Union{Float64, Missings.Missing},1},Array{Union{Missings.Missing, ODBC.API.SQLDate},1},Array{Union{Missings.Missing, ODBC.API.SQLTimestamp},1},Array{Union{Missings.Missing, ODBC.API.SQLTimestamp},1},Array{Union{Missings.Missing, ODBC.API.SQLTime},1},Array{Union{Int16, Missings.Missing},1},WeakRefStrings.WeakRefStringArray{WeakRefString{UInt8},1,Missings.Missing},WeakRefStrings.WeakRefStringArray{WeakRefString{UInt8},1,Missings.Missing},Array{Union{Array{UInt8,1}, Missings.Missing},1},Array{Union{Array{UInt8,1}, Missings.Missing},1},Array{Union{Array{UInt8,1}, Missings.Missing},1},Array{Union{Array{UInt8,1}, Missings.Missing},1},Array{Union{Array{UInt8,1}, Missings.Missing},1},Array{Union{Array{UInt8,1}, Missings.Missing},1},Array{Union{Missings.Missing, String},1},Array{Union{Missings.Missing, String},1},Array{Union{Missings.Missing, String},1},Array{Union{Missings.Missing, String},1}}}, ::Type{DataStreams.Data.Field}, ::Type{Union{Int64, Missings.Missing}}, ::Int64, ::Int64) at /Users/username/.julia/v0.6/ODBC/src/Source.jl:323
   [3] macro expansion at /Users/username/.julia/v0.6/DataStreams/src/DataStreams.jl:542 [inlined]
   [4] stream!(::ODBC.Source{Tuple{Array{Union{Int64, Missings.Missing},1},Array{Union{Int8, Missings.Missing},1},Array{Union{DecFP.Dec64, Missings.Missing},1},Array{Union{Int32, Missings.Missing},1},Array{Union{DecFP.Dec64, Missings.Missing},1},Array{Union{Int16, Missings.Missing},1},Array{Union{Int32, Missings.Missing},1},Array{Union{Int8, Missings.Missing},1},Array{Union{Float32, Missings.Missing},1},Array{Union{Float64, Missings.Missing},1},Array{Union{Missings.Missing, ODBC.API.SQLDate},1},Array{Union{Missings.Missing, ODBC.API.SQLTimestamp},1},Array{Union{Missings.Missing, ODBC.API.SQLTimestamp},1},Array{Union{Missings.Missing, ODBC.API.SQLTime},1},Array{Union{Int16, Missings.Missing},1},WeakRefStrings.WeakRefStringArray{WeakRefString{UInt8},1,Missings.Missing},WeakRefStrings.WeakRefStringArray{WeakRefString{UInt8},1,Missings.Missing},Array{Union{Array{UInt8,1}, Missings.Missing},1},Array{Union{Array{UInt8,1}, Missings.Missing},1},Array{Union{Array{UInt8,1}, Missings.Missing},1},Array{Union{Array{UInt8,1}, Missings.Missing},1},Array{Union{Array{UInt8,1}, Missings.Missing},1},Array{Union{Array{UInt8,1}, Missings.Missing},1},Array{Union{Missings.Missing, String},1},Array{Union{Missings.Missing, String},1},Array{Union{Missings.Missing, String},1},Array{Union{Missings.Missing, String},1}}}, ::Type{DataStreams.Data.Field}, ::CSV.Sink{Void,DataType}, ::DataStreams.Data.Schema{true,Tuple{Union{Int64, Missings.Missing},Union{Int8, Missings.Missing},Union{DecFP.Dec64, Missings.Missing},Union{Int32, Missings.Missing},Union{DecFP.Dec64, Missings.Missing},Union{Int16, Missings.Missing},Union{Int32, Missings.Missing},Union{Int8, Missings.Missing},Union{Float32, Missings.Missing},Union{Float64, Missings.Missing},Union{Missings.Missing, ODBC.API.SQLDate},Union{Missings.Missing, ODBC.API.SQLTimestamp},Union{Missings.Missing, ODBC.API.SQLTimestamp},Union{Missings.Missing, ODBC.API.SQLTime},Union{Int16, Missings.Missing},Union{Missings.Missing, WeakRefString{UInt8}},Union{Missings.Missing, WeakRefString{UInt8}},Union{Array{UInt8,1}, Missings.Missing},Union{Array{UInt8,1}, Missings.Missing},Union{Array{UInt8,1}, Missings.Missing},Union{Array{UInt8,1}, Missings.Missing},Union{Array{UInt8,1}, Missings.Missing},Union{Array{UInt8,1}, Missings.Missing},Union{Missings.Missing, String},Union{Missings.Missing, String},Union{Missings.Missing, String},Union{Missings.Missing, String}}}, ::Int64, ::NTuple{27,Base.#identity}, ::DataStreams.Data.##15#16, ::Array{Any,1}, ::Type{Ref{(:test_bigint, :test_bit, :test_decimal, :test_int, :test_numeric, :test_smallint, :test_mediumint, :test_tiny_int, :test_float, :test_real, :test_date, :test_datetime, :test_timestamp, :test_time, :test_year, :test_char, :test_varchar, :test_binary, :test_varbinary, :test_tinyblob, :test_blob, :test_mediumblob, :test_longblob, :test_tinytext, :test_text, :test_mediumtext, :test_longtext)}}) at /Users/username/.julia/v0.6/DataStreams/src/DataStreams.jl:614
   [5] #stream!#18(::Bool, ::Dict{Int64,Function}, ::Function, ::Array{Any,1}, ::Function, ::ODBC.Source{Tuple{Array{Union{Int64, Missings.Missing},1},Array{Union{Int8, Missings.Missing},1},Array{Union{DecFP.Dec64, Missings.Missing},1},Array{Union{Int32, Missings.Missing},1},Array{Union{DecFP.Dec64, Missings.Missing},1},Array{Union{Int16, Missings.Missing},1},Array{Union{Int32, Missings.Missing},1},Array{Union{Int8, Missings.Missing},1},Array{Union{Float32, Missings.Missing},1},Array{Union{Float64, Missings.Missing},1},Array{Union{Missings.Missing, ODBC.API.SQLDate},1},Array{Union{Missings.Missing, ODBC.API.SQLTimestamp},1},Array{Union{Missings.Missing, ODBC.API.SQLTimestamp},1},Array{Union{Missings.Missing, ODBC.API.SQLTime},1},Array{Union{Int16, Missings.Missing},1},WeakRefStrings.WeakRefStringArray{WeakRefString{UInt8},1,Missings.Missing},WeakRefStrings.WeakRefStringArray{WeakRefString{UInt8},1,Missings.Missing},Array{Union{Array{UInt8,1}, Missings.Missing},1},Array{Union{Array{UInt8,1}, Missings.Missing},1},Array{Union{Array{UInt8,1}, Missings.Missing},1},Array{Union{Array{UInt8,1}, Missings.Missing},1},Array{Union{Array{UInt8,1}, Missings.Missing},1},Array{Union{Array{UInt8,1}, Missings.Missing},1},Array{Union{Missings.Missing, String},1},Array{Union{Missings.Missing, String},1},Array{Union{Missings.Missing, String},1},Array{Union{Missings.Missing, String},1}}}, ::CSV.Sink{Void,DataType}) at /Users/username/.julia/v0.6/DataStreams/src/DataStreams.jl:516
   [6] stream!(::ODBC.Source{Tuple{Array{Union{Int64, Missings.Missing},1},Array{Union{Int8, Missings.Missing},1},Array{Union{DecFP.Dec64, Missings.Missing},1},Array{Union{Int32, Missings.Missing},1},Array{Union{DecFP.Dec64, Missings.Missing},1},Array{Union{Int16, Missings.Missing},1},Array{Union{Int32, Missings.Missing},1},Array{Union{Int8, Missings.Missing},1},Array{Union{Float32, Missings.Missing},1},Array{Union{Float64, Missings.Missing},1},Array{Union{Missings.Missing, ODBC.API.SQLDate},1},Array{Union{Missings.Missing, ODBC.API.SQLTimestamp},1},Array{Union{Missings.Missing, ODBC.API.SQLTimestamp},1},Array{Union{Missings.Missing, ODBC.API.SQLTime},1},Array{Union{Int16, Missings.Missing},1},WeakRefStrings.WeakRefStringArray{WeakRefString{UInt8},1,Missings.Missing},WeakRefStrings.WeakRefStringArray{WeakRefString{UInt8},1,Missings.Missing},Array{Union{Array{UInt8,1}, Missings.Missing},1},Array{Union{Array{UInt8,1}, Missings.Missing},1},Array{Union{Array{UInt8,1}, Missings.Missing},1},Array{Union{Array{UInt8,1}, Missings.Missing},1},Array{Union{Array{UInt8,1}, Missings.Missing},1},Array{Union{Array{UInt8,1}, Missings.Missing},1},Array{Union{Missings.Missing, String},1},Array{Union{Missings.Missing, String},1},Array{Union{Missings.Missing, String},1},Array{Union{Missings.Missing, String},1}}}, ::CSV.Sink{Void,DataType}) at /Users/username/.julia/v0.6/DataStreams/src/DataStreams.jl:501
```

### PR DESCRIPTION
**Pull request by nicoleepp**
Ok this is ready to review again.

Closes #196 (see second commit)
Closes #183 (see third commit)

Did these together because I added tests that stream to CSV (see first commit) that were useful to both issues.

Some other minor improvements were (see first commit):

-  Moved odbc.ini and odbcinst.ini test files into a `/test/setup/` directory
-  Moved the data file used for testing into `/test/data/`

### CODE REVIEW

File: src/Source.jl [hunk 1]
```diff
@@ -320,13 +320,20 @@ Data.streamtype(::Type{ODBC.Source}, ::Type{Data.Column}) = true
 Data.streamtype(::Type{ODBC.Source}, ::Type{Data.Field}) = true
 
 function Data.streamfrom(source::ODBC.Source, ::Type{Data.Field}, ::Type{Union{T, Missing}}, row, col) where {T}
-    val = source.columns[col][row - source.rowoffset]::Union{T, Missing}
+    val = if isempty(source.columns[col])
```
Comment (quinnj) [inline src/Source.jl]: I'm having a hard time walking thru the logic of the changes right here specifically; can you help me understand why this needs ot change?

Comment (nicoleepp) [reply src/Source.jl]: @quinnj Sure, this particular case happens the first time `streamfrom` gets called, `source.columns[col]` is just an empty array (nothing is fetched), which causes this error: 

```julia
BoundsError: attempt to access 0-element Array{Union{Int64, Missings.Missing},1} at index [1]
```
Full stacktrace here: #196 

Let me know if you have any ideas of a better way to fix this.
